[build]
  command = "react-router build"
  publish = "build/client"
  functions = "build/server"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "react-router dev"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true